# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runIntegrationTestsOnCodingCI:
    name: trigger integration tests on coding.net CI
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl -u ${{ secrets.CODING_CI_TOKEN }} \
            -v -X POST  'https://sftest11.coding.net/api/cci/job/399367/trigger' \
            -H 'Content-Type: application/json' \
            -d '
              {
              "ref": "main",
              "envs": []
            }'
